### ISSUE TITLE
NCTR Enable Switch Output not functioning

### ISSUE THREAD

**Issue by MadKreator37** [HeliosProfiles/DCS-F-15E-Profile-by-MadKreator37#10]
Helios: 1.6.606
DCS: Newest

Issue: Left BulkHead NCTR Enable switch has no OUTPUT to DCS. Input is functioning correctly.
ID: 524
deviceId: 17
actionID: 3524

Interface seems correct. looked in clickabledata.lua but could not find "actionID's/ commands/ button numbers" to verify

**Comment by BlueFinBima** [comment]
Not sure whether this has ever worked, however the current deviceID is 3 so this needs to be fixed in the interface.

**Comment by BlueFinBima** [comment]
Fixed in Helios commit [579ee3749963eac9318878d6f890910d9777130d](https://github.com/HeliosVirtualCockpit/Helios/commit/579ee3749963eac9318878d6f890910d9777130d)
Likely to ship in 1.6.607
