### ISSUE TITLE
HUD Reject switch binding

### ISSUE THREAD

**Issue by MadKreator37** [HeliosProfiles/DCS-F-15E-Profile-by-MadKreator37#4]
HUD symbology reject switch on Pilot UFC reversed. Opposite movement between Helios switch and in-game switch. Switch does not seem to be implemented at this time, though.

**Comment by BlueFinBima** [comment]
@MadKreator37 Typically the issue is raised against the repo with the error.  I suggest you close this as a duplicate of https://github.com/HeliosVirtualCockpit/Helios/issues/753
